connection/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = 'connection'
urlpatterns = [
    path('', views.index, name='index'),
    path('success/', views.success, name='success'),
    path('name/create/', views.NameCreate.as_view(), name='name-create'),
    path('name/<int:pk>/update/',
         views.NameUpdate.as_view(), name='name-update'),
    path('name/<int:pk>/delete/',
         views.NameDelete.as_view(), name='name-delete'),
    path('name/<int:pk>/', views.NameDetailView.as_view(), name='name-detail'),
    path('name/', views.NameListView.as_view(), name='name'),
    path('contact/', views.contact_form, name="connection-contact"),

    path('country/',
         cache_page(10)(views.CountryCityList.as_view()), name='country')
]

djangoProject_test/urls.py
import debug_toolbar

from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('connection/', include('connection.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        path('silk/', include('silk.urls', namespace='silk')),
    ]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('triangle/', views.contact_form, name='triangle'),
    path('person/', views.authorization_form, name='person'),
    path('reminder/', views.reminder_data_form, name='reminder'),
    path('person/<int:id>/', views.output_personal_data, name='person'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
            integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf"
            crossorigin="anonymous"></script>
{% load static %}
{% block extra_js %}
    <script src="{% static 'js/contact_ajax.js' %}"></script>
{% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">Connection</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'connection:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'connection:name' %}">All names</a>
      </li>
      <li class="nav-item">
          <a class="nav-link js-connection-contact" data-url="{% url 'connection:connection-contact' %}">Contact</a>
      </li>
    </ul>
    <div>
        <ul class="nav navbar-nav dropdown-menu-dark navbar-dark dropdown dropdown-toggle-split ">
        <li class="nav-item ">
          <a class="nav-link dropdown-toggle " href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
          </a>
          <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-right"   aria-labelledby="navbarDarkDropdownMenuLink">
            <li><a class="dropdown-item " href="{% url 'connection:name-create' %}">Create name</a></li>
            <li><a class="dropdown-item " href="{% url 'connection:country' %}">All country and city</a></li>
          </ul>
        </li>
      </ul>
    </div>


  </div>
</nav>
<div class="container-fluid">

          {% if messages %}
            <div class="row">
                <div class="col-sm-12">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                            <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}
                                {{ message.tags|title }}{% endif %}!</strong> {{ message }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
</div>
</div>
{% block content %}{% endblock %}
{% block modal %}
    <div class="modal fade" id="connection-contact">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Local Connection Home</h1>

    {% load poll_extras %}
    {% parsing_output as li %}
    {% for i in li %}
        <p> {{ i }}</p>
    {% endfor %}
    {% filter replace_func %} Hi, absterging, you make abstinence {% endfilter %}
  <h2>Dynamic content</h2>

  <p>The Connection has the following record names, countries, cities:</p>
    <ul>
        <li><strong>Names:</strong> {{ num_names }}</li>
        <li><strong>Country:</strong> {{ num_country }}</li>
        <li><strong>City:</strong> {{ num_city }}</li>
    </ul>
  You have visited this page {{ num_visits }} time{% if num_visits > 1 %}s{% endif %}.
{% endblock %}